<?php
//  http://rcm.amazon.com/e/cm?t='.lz::$c['awstag'].'&o=1&p=
$ads468=array(
	    	'13&l=ur1&category=apparel&banner=1BBFJJPF53XW9ZMPFA82&f=ifr'=>'Apparel & Accessories',
		'13&l=ur1&category=automotive&banner=1Y5GNARHWSEWA940B702&f=ifr'=>'Automotive',
		'13&l=ur1&category=baby&banner=1KKKKDC3NCGCQVXX6RR2&f=ifr'=>'Baby',
		'13&l=ur1&category=babyregistry&banner=1KKHXVQKHTDGFRGBYM02&f=ifr'=>'Baby Registry',
		'26&l=ur1&category=school&banner=0V4J2QYAQQRT6VYZ9K82&f=ifr'=>'Back to School/Off to College',
		'13&l=ur1&category=beauty&banner=17TAWVQYE1E5W96A8W82&f=ifr'=>'Beauty',
		'26&l=ur1&category=books&banner=0GDEZK2MM2XGCEH7M202&f=ifr'=>'Books',
		'13&l=ur1&category=wireless&banner=0SESQPYNEXXSWMYDWG02&f=ifr'=>'Cell Phones',
		'26&l=ur1&category=computers_accesories&banner=12CKQQKWNWBNQ20V9X02&f=ifr'=>'Computers & Accessories',
		'13&l=ur1&category=dvd&banner=1Y6X580CSWSE2JYBZ6R2&f=ifr'=>'DVD',
		'13&l=ur1&category=electronics&banner=0JS3Z2NDQ4D78G5E5CG2&f=ifr'=>'Electronics',
		'13&l=ur1&category=gourmet&banner=05HSXBAM75NQEPYG6682&f=ifr'=>'Gourmet Food',
		'13&l=ur1&category=grocery&banner=0YYKD4EARRDKDREAQR82&f=ifr'=>'Grocery',
		'13&l=ur1&category=health&banner=1FBWF8DVB1Y8TH3YE3R2&f=ifr'=>'Health & Personal Care',
		'13&l=ur1&category=homegarden&banner=0ZTKWP400KVSXZMDYN82&f=ifr'=>'Home & Garden',
		'26&l=ur1&category=homeaudiohometheater&banner=16F0Y5VWA95TJ0V6MH82&f=ifr'=>'Home Audio & Home Theater',
		'13&l=ur1&category=industrialscientific&banner=0MZFH8BXWENX5RKSVZ02&f=ifr'=>'Industrial & Scientific',
		'26&l=ur1&category=jewelry&banner=1F07686QJ1QZXN1EHQR2&f=ifr'=>'Jewelry',
		'13&l=ur1&category=kitchen&banner=0J9GCWM56ZWRSPYPWS82&f=ifr'=>'Kitchen & Housewares',
		'26&l=ur1&category=motorcycleatv&banner=1YV0V1J313604Y7X2FR2&f=ifr'=>'Motorcycle & ATV',
		'26&l=ur1&category=outdoorrecreation&banner=0CDY3FGJ2PD68NJXFKG2&f=ifr'=>'Outdoor Recreation',
		'13&l=ur1&category=pets&banner=1EWNPJG0FSETT2VN6TG2&f=ifr'=>'Pets',
		'26&l=ur1&category=shoes&banner=0Q046BNJ8N365747AM82&f=ifr'=>'Shoes',
		'13&l=ur1&category=software&banner=19B9W0V74Z9KV3E29MR2&f=ifr'=>'Software',
		'13&l=ur1&category=sports&banner=1FG4SKMXKH8ANN37MB82&f=ifr'=>'Sports & Outdoors',
		'13&l=ur1&category=sss&banner=0RH3RXX3AS9J8YGKQER2&f=ifr'=>'Super Saver Shipping',
		'11&l=ur1&category=textbooks&banner=17P1AE8RQ1T7ZFC62V82&f=ifr'=>'Textbooks',
		'13&l=ur1&category=tools&banner=0PY4E6R6W1N39TWJ6A02&f=ifr'=>'Tools & Hardware',
		'13&l=ur1&category=toysandgames&banner=091DNYMZVS7SNWRS6FG2&f=ifr'=>'Toys & Games',
		'26&l=ur1&category=videogames&banner=0CATR8RV2267Q09F3MR2&f=ifr'=>'Video Games',
		'26&l=ur1&category=watches&banner=0YQ2X2CKQRZRAD3RQBG2&f=ifr'=>'Watches',
		'13&l=ur1&category=wedding&banner=08PAJEFXH10TYXPW7NG2&f=ifr'=>'Wedding Registry',

	    );

$ads120=array(
		'29&l=ur1&category=apparel&banner=0HSW9W6HM5MBWR5MCX02&f=ifr'=>'Apparel & Accessories',
		'29&l=ur1&category=automotive&banner=1Y355NYEB9YYCAKAC702&f=ifr'=>'Automotive',
		'29&l=ur1&category=baby&banner=09S5S2PWFD9KQKT18SR2&f=ifr'=>'Baby',
		'14&l=ur1&category=carelectronics&banner=13PB38VVDK8PNJC7GG02&f=ifr'=>'Car Electronics',
		'29&l=ur1&category=wireless&banner=0FKKRJZ0YH58FNCZSDR2&f=ifr'=>'Cell Phones',
		'29&l=ur1&category=computers_accesories&banner=0C26K37C3GHZ3WZT9Q02&f=ifr'=>'Computers & Accessories',
		'29&l=ur1&category=dvd&banner=1GM7J5TZSG5X8AQRXX02&f=ifr'=>'DVD',
		'29&l=ur1&category=electronics&banner=0YBN5Z6TQKJSDQQHWN02&f=ifr'=>'Electronics',	    
		'29&l=ur1&category=homegarden&banner=1F8MX0MPDHRKM89BF3G2&f=ifr'=>'Home & Garden',
		'29&l=ur1&category=homeaudiohometheater&banner=0T4YJ6YBNCMJM9GGAK02&f=ifr'=>'Home Audio & Home Theater',
		'29&l=ur1&category=kitchen&banner=02B8WKTC39E2Q4QGNEG2&f=ifr'=>'Kitchen & Housewares',
		'29&l=ur1&category=motorcycleatv&banner=1NPSSPD8CR40CVQSCK82&f=ifr'=>'Motorcycle & ATV',
		'29&l=ur1&category=officeschoolsupplies&banner=0TJYD8VHF6DPGHN3YB02&f=ifr'=>'Office & School Supplies',
		'29&l=ur1&category=outdoorrecreation&banner=054N4NGXCVYM010KSC02&f=ifr'=>'Outdoor Recreation',
		'29&l=ur1&category=patiolawngarden&banner=1KTCZRXD8GSACH8Q8782&f=ifr'=>'Patio, Lawn & Garden',
		'29&l=ur1&category=pets&banner=1HQX46CSHMPJYSYMDSR2&f=ifr'=>'Pets',
		'29&l=ur1&category=shoes&banner=01H7SW8X99RPYMYSJBR2&f=ifr'=>'Shoes',
		'11&l=ur1&category=textbooks&banner=17P1AE8RQ1T7ZFC62V82&f=ifr'=>'Textbooks',
		'29&l=ur1&category=videogames&banner=1GTQDNRRV15Q0M822M02&f=ifr'=>'Video Games',
		
		);

$mode=array('apparel'=>'Apparel &amp; Accessories',
'automotive'=>'Automotive',
'baby'=>'Baby',
'beauty'=>'Beauty',
'books'=>'Books',
'photo'=>'Camera &amp; Photo',
'wireless-phones'=>'Cell Phones &amp; Service',
'classical'=>'Classical Music',
'pc-hardware'=>'Computers',
'dvd'=>'DVD',
'electronics'=>'Electronics',
'gourmet'=>'Gourmet Food',
'grocery'=>'Grocery',
'garden'=>'Home &amp; Garden',
'hpc'=>'Health &amp; Personal Care',
'industrial'=>'Industrial &amp; Scientific',
'jewelry'=>'Jewelry',
'kindle'=>'Kindle Store',
'kitchen'=>'Kitchen &amp; Housewares',
'magazines'=>'Magazine Subscriptions',
'universal'=>'Miscellaneous',
'digital-music'=>'MP3 Downloads',
'music'=>'Music',
'mi'=>'Musical Instruments',
'office-products'=>'Office Products',
'shoes'=>'Shoes',
'software'=>'Software',
'sporting'=>'Sports &amp; Outdoors',
'tools'=>'Tools &amp; Hardware',
'toys'=>'Toys &amp; Games',
'vhs'=>'VHS',
'amazontv'=>'Video On Demand Videos',
'videogames'=>'Video Games',
'watches'=>'Watches',
'wireless-accessories'=>'Wireless Accessories');



$delay=array(
'rating'=>5,
'error'=>15,
);
?>